<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Xilium.CefGlue.BrowserProcess.Core</AssemblyName>
    <RootNamespace>Xilium.CefGlue.BrowserProcess</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <NoWarn>$(NoWarn);CS0168</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CefGlue.Core/CefGlue.Core.csproj" />
    <ProjectReference Include="../CefGlue.Common.Shared/CefGlue.Common.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tarui.WebView.CefGlueNext" />
  </ItemGroup>
</Project>
