<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\Tarui.Contracts\Tarui.Contracts.csproj" />
    <ProjectReference Include="..\..\core\Tarui.Ipc\Tarui.Ipc.csproj" />
    <ProjectReference Include="..\..\generators\Tarui.Ipc.Generators\Tarui.Ipc.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
