<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tarui.WebView.Native</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
    <ProjectReference Include="..\Tarui.WebView.Abstractions\Tarui.WebView.Abstractions.csproj" />
  </ItemGroup>
</Project>
