<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tarui.WebView.CefGlueNext</RootNamespace>
    <AssemblyName>Tarui.WebView.CefGlueNext</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Tarui.WebView.Abstractions/Tarui.WebView.Abstractions.csproj" />
    <ProjectReference Include="../Tarui.WebView.Avalonia/Tarui.WebView.Avalonia.csproj" />
    <ProjectReference Include="../CefGlue.Next.Avalonia/CefGlue.Next.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tarui.WebView.Tests" />
  </ItemGroup>
</Project>
