using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Tarui.Ipc.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class TaruiCommandCatalogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Tarui.Contracts.TaruiCommandAttribute",
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax,
                static (attributeContext, _) => ReadCommand(attributeContext.TargetSymbol))
            .Where(static name => name is not null)
            .Select(static (name, _) => name!);

        context.RegisterSourceOutput(commands.Collect(), static (productionContext, names) =>
            EmitCatalog(productionContext, names));
    }

    private static string? ReadCommand(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "Tarui.Contracts.TaruiCommandAttribute")
            {
                continue;
            }

            return attribute.ConstructorArguments.Length == 1
                ? attribute.ConstructorArguments[0].Value as string
                : null;
        }

        return null;
    }

    private static void EmitCatalog(
        SourceProductionContext context,
        ImmutableArray<string> names)
    {
        var distinctNames = names
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static name => name, StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine();
        source.AppendLine("namespace Tarui.Generated;");
        source.AppendLine();
        source.AppendLine("public static class GeneratedCommandCatalog");
        source.AppendLine("{");
        source.AppendLine("    public static IReadOnlyList<string> Commands { get; } =");
        source.AppendLine("    [");

        foreach (var name in distinctNames)
        {
            source.Append("        ");
            source.Append('"');
            source.Append(Escape(name));
            source.Append('"');
            source.AppendLine(",");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");

        context.AddSource("GeneratedCommandCatalog.g.cs", source.ToString());
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r", "\\r")
        .Replace("\n", "\\n");
}
