<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Xilium.CefGlue.Common.Shared</AssemblyName>
    <RootNamespace>Xilium.CefGlue.Common.Shared</RootNamespace>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CefGlue.Core/CefGlue.Core.csproj" />
  </ItemGroup>
</Project>
